language: php
install:
  - pear install package.xml
php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
matrix:
  include:
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
script: phpunit tests/